name: l0bby_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/running_tree.png
    - lib/assets/
    - lib/assets/images/
    - lib/assets/courts/
  fonts:
    - family: BACKTO1982
      fonts:
        - asset: lib/fonts/BACKTO1982.ttf
          weight: 700
    - family: INVASION2000
      fonts:
        - asset: lib/fonts/INVASION2000.ttf
          weight: 700
    - family: Karma Suture
      fonts:
        - asset: lib/fonts/Karma Suture.otf
          weight: 700
    - family: gomarice_goma_block
      fonts:
        - asset: lib/fonts/gomarice_goma_block.ttf
          weight: 700